Controllers/CMS/SystemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Xml;
using System.Net;
using System.Net.Sockets;
using System.Xml.Linq;
using System.Data.SqlClient;
using System.Data;
using System.Web.Security;
using Webdiyer.WebControls.Mvc;

namespace NationalIT.Controllers
{
    public class SystemController : BaseController
    {
        //
        // GET: /System/
        [Authorize]
        [ValidationFunction(ActionName.SystemAdmin)]
        [HttpGet]
        public ActionResult SetUpFolderBackUp()
        {
            // Đường dẫn tới file xml.
            string fileName = HttpContext.Server.MapPath("~/App_Data/config.xml");
            if (!System.IO.File.Exists(fileName))
            {
                CrearDocumentoXML(fileName);
            }
            // Tạo một đối tượng TextReader mới
            var xtr = System.Xml.Linq.XDocument.Load(fileName);
            string path_backup = "";
            // string passwordsso = "";
            //bool useOtherMailServer = false;
            var config = xtr.Elements("system.config").FirstOrDefault();
            try
            {
                if (config.Descendants("path-backup").Any())
                    path_backup = config.Element("path-backup").Value.Trim();
            }
            catch (Exception ex)
            {
                return View();
            }
            var model = new Models.SystemModel()
            {
                PathBackupFolder = path_backup
            };
            return View(model);
        }

        [Authorize]
        [ValidationFunction(ActionName.SystemAdmin)]
        [HttpPost]
        public ActionResult SetUpFolderBackUp(Models.SystemModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    // Đường dẫn tới file xml.
                    string fileName = System.Web.Hosting.HostingEnvironment.ApplicationPhysicalPath + "/App_Data/config.xml";
                    if (!System.IO.File.Exists(fileName))
                    {
                        CrearDocumentoXML(fileName);
                    }
                    // Tạo một đối tượng TextReader mới
                    var xtr = System.Xml.Linq.XDocument.Load(fileName);
                    if (!xtr.Descendants("system.config").Any())
                    {
                        XElement EmailElement = new XElement("system.config");
                        xtr.Add(EmailElement);
                    }
                    var config = xtr.Elements("system.config").FirstOrDefault();

                    string path_backup = model.PathBackupFolder;

                    if (path_backup.LastIndexOf("\\") != path_backup.Length - 1)
                    {
                        path_backup += "\\";
                    }
                    if (!string.IsNullOrEmpty(path_backup))
                    {
                        if (!config.Descendants("path-backup").Any())
                        {
                            XElement passElement = new XElement("path-backup");
                            passElement.Value = path_backup;
                            config.Add(passElement);
                        }
                        else
                        {
                            config.SetElementValue("path-backup", path_backup);
                        }
                    }

                    xtr.Save(fileName);

                    try
                    {
                        if (!System.IO.Directory.Exists(model.PathBackupFolder))
                            System.IO.Directory.CreateDirectory(model.PathBackupFolder);
                    }
                    catch { }

                    return RedirectToAction("Index", "Config");
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", "Error system. Please try again a few minutes.");
                }
            }
            return View(model);
        }
    }
}

Views/System/PayrollLog.cshtml
@using Webdiyer.WebControls.Mvc
@model PagedList<NationalIT.PayrollProcessingLog>
<h3>
    Processing Payroll log</h3>
<div class="f_req">@ViewBag.Error</div>
<div class="row-fluid">
    <div class="span12">
        <div class="row-fluid">
            <div class="span12">
                @if ((bool)ViewBag.ShowButtonDelete)
                {
                    @Html.ActionLink("Delete", "Delete", null, new { @class = "btn btn-danger DeleteItem confirmDelete" })
                }
            </div>
        </div>
        <table class="table">
            <tr>
                <th>
                    <input type="checkbox" name="" value="" class="checkAll" />
                </th>
                <th>
                    Payroll amount
                </th>
                <th>
                    Driver name
                </th>
                <th>
                    User perform
                </th>
                <th>
                    Action
                </th>
                <th>
                    Date
                </th>
            </tr>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        <input type="checkbox" name="checkOwner" value="@item.ID" class="checkitem"/>
                    </td>
                    <td>
                        @if (!item.Deleted)
                        {
                            @Html.ActionLink(String.Format("{0:C}", item.PayrollAmount) + "", "PayrollsRollBack", "DriverInfo",new { id = item.TempReportID, driverID = item.DriverID },null)
                        }
                        else
                        {
                            @(String.Format("{0:C}", item.PayrollAmount))
                        }
                    </td>
                    <td>
                        @item.DriverName
                    </td>
                    <td>
                        @item.UserName
                    </td>
                    <td>
                        @if (item.Deleted)
                        {
                            <span class="error">@item.Action</span>
                        }
                        else
                        {
                            @(item.Action)
                        }
                    </td>
                    <td>
                        @item.Date.ToString("MM/dd/yyyy HH:mm")
                    </td>
                </tr>
            }
        </table>
        <div class="row-fluid">
            <div class="span4">
                <div class="dataTables_info">
                    @if (Model.TotalItemCount > 0)
                    {
                        if (Model.TotalItemCount < Model.PageSize)
                        {
                        <span>1 </span>
                        <span>- </span>@Model.TotalItemCount
                        }
                        else
                        {
                        <span></span>@((Model.CurrentPageIndex - 1) * Model.PageSize + 1)
                        <span>- </span>@((Model.CurrentPageIndex != Model.TotalPageCount) ? (Model.CurrentPageIndex * Model.PageSize) : Math.Abs((Model.CurrentPageIndex) * Model.PageSize - (Model.PageSize * Model.TotalPageCount) - Model.TotalItemCount))
                        }
                        <span>of </span>@(Model.TotalItemCount)                            
                    }
                </div>
            </div>
            <div class="span8">
                <div class="dataTables_paginate paging_bootstrap pagination phantrangmvcpager">
                    @Html.Pager(Model, new PagerOptions { ContainerTagName = "ul", PageIndexParameterName = "page", CurrentPagerItemWrapperFormatString = "<li class='active'>{0}</li>", CurrentPageNumberFormatString = "{0}", FirstPageText = "&laquo; ", LastPageText = " &raquo;", NextPageText = "Next →", PrevPageText = "← Prev", SeparatorHtml = "" })
                </div>
            </div>
        </div>
    </div>
</div>

Views/System/SetUpFolderBackUp.cshtml
@model NationalIT.Models.SystemModel
@{
    ViewBag.Title = "Config folder backup database";
}
<div id="ThongBao">
    <h3 class="heading">
        @ViewBag.Title</h3>
    @using (Html.BeginForm("SetUpFolderBackUp", "System"))
    {            
        <div class="row-fluid">
            <div class="span12">
                <label class="" for="PathBackupFolder">
                    Folder contains file backup</label>
                <div class="span12 input-prepend" style="margin-left: 0">
                    @Html.TextBoxFor(Model => Model.PathBackupFolder, new { Class = "span8", @placeholder = "Enter filepath folder contains file backup" })
                    <span class="help-block">@Html.ValidationMessageFor(model => model.PathBackupFolder)</span>
                </div>
            </div>
        </div>
        <div class="control-group">
            <div class="controls">
                <button class="btn btn-info" type="submit" onclick="$('#loadingBefore').html($('.waiting').html());">
                    Save</button>
                <a class="btn" href="/Config">
                    Cancel</a>
            </div>
        </div>
    }
</div>