Controllers/BackupAndRestoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.ComponentModel.DataAnnotations;
using System.Xml.Linq;
using System.Web.Configuration;
using System.IO;
using NationalIT.Models;
using System.Data.SqlClient;
using System.Configuration;

namespace NationalIT.Controllers
{
    public class BackupAndRestoreController : BaseController
    {
        //
        // GET: /BackupAndRestore/
        [Authorize]
        [ValidationFunction(ActionName.BACKUPDATABASE, ActionName.RESTOREDATABASE)]
        public ActionResult Index()
        {
            try
            {
                string FilePathXML = HttpContext.Server.MapPath("~/App_Data/config.xml");
                var doc = XDocument.Load(FilePathXML);
                bool isAdmin = CurrentUser.UserName.Equals(UserDAL.ADMIN);
                ViewBag.ShowBackupMenu = IsFunctionInRole(ActionName.BACKUPDATABASE.ToString()) || isAdmin;
                ViewBag.ShowDeleteMenu = ViewBag.ShowRestoreMenu = IsFunctionInRole(ActionName.RESTOREDATABASE.ToString()) || isAdmin;
                string folderName = doc.Element("system.config").Element("path-backup").Value;
                string[] files = Directory.GetFiles(folderName);
                var list = new List<BackupModel>();
                DirectoryInfo di = new DirectoryInfo(folderName);
                foreach (FileInfo item in di.GetFiles())
                {
                    BackupModel tmp = new BackupModel()
                    {
                        Name = item.Name,
                        Date = item.LastWriteTime.ToShortDateString(),
                    };
                    list.Add(tmp);
                }
                list = list.OrderByDescending(m => m.Date).ToList();
                if (Request.IsAjaxRequest())
                {
                    return PartialView("_RestorePartial", list);
                }
                return View(list);
            }
            catch { return View(); }
        }

        [Authorize]
        [ValidationFunction(ActionName.BACKUPDATABASE)]
        public ActionResult Backup()
        {
            DateTime now = DateTime.Now;
            string NameBak = "Backup_" + DateTime.Now.ToString("yyyy-MM-dd") + "_" + now.Hour + "-" + now.Minute + "-" + now.Second + ".bak";
            return View(new BackupModel { Name = NameBak });
        }

        [HttpPost]
        [Authorize]
        [ValidationFunction(ActionName.BACKUPDATABASE)]
        public ActionResult Backup(BackupModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    if (model.Name.Contains("\\"))
                    {
                        ModelState.AddModelError("Name", "File name must not contain one of the following characters /\\:*?\"<>|");
                        return PartialView(model);
                    }
                    // Đường dẫn tới file xml.
                    string path = System.Web.Hosting.HostingEnvironment.ApplicationPhysicalPath + "/App_Data/config.xml";
                    // Tạo một đối tượng TextReader mới
                    var xtr = System.Xml.Linq.XDocument.Load(path);
                    string backupFolder = string.Format(xtr.Element("system.config").Element("path-backup").Value.Trim());   //Vuongj
                    // tạo folder backup neu chua co
                    if (!System.IO.Directory.Exists(backupFolder))
                    {
                        System.IO.Directory.CreateDirectory(backupFolder);
                    }

                    string fileName = model.Name;
                    if (fileName.IndexOf(".bak") <= 0)
                    {
                        fileName += ".bak";
                    }

                    var filePath = backupFolder;
                    if (filePath.LastIndexOf("\\") == filePath.Length - 1)
                    {
                        filePath += fileName;
                    }
                    else
                    {
                        filePath += "\\" + fileName;
                    }

                    String conStr = ConfigurationManager.ConnectionStrings["ApplicationServices"].ConnectionString;
                    SqlConnectionStringBuilder builder = new SqlConnectionStringBuilder(conStr);
                    string databaseName = builder.InitialCatalog;

                    string query = string.Format(@"BACKUP DATABASE {0} TO DISK = '{1}' WITH INIT", databaseName, filePath);
                    int result = DB.Entities.ExecuteStoreCommand(query);
                    if (result != 0)
                    {
                        //add to Data.xml
                        var backupObj = new Models.BackupModel();
                        backupObj.Name = model.Name;
                        backupObj.FilePath = filePath;
                        backupObj.Date = DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss");
                        return RedirectToAction("Index");
                    }
                }
                catch (Exception ex)
                {
                    if (ex.Message.Contains("Cannot open backup device"))
                    {
                        // Đường dẫn tới file xml.
                        string path = System.Web.Hosting.HostingEnvironment.ApplicationPhysicalPath + "/App_Data/config.xml";
                        // Tạo một đối tượng TextReader mới
                        var xtr = System.Xml.Linq.XDocument.Load(path);
                        string backupFolder = string.Format(xtr.Element("system.config").Element("path-backup").Value.Trim());
                        ModelState.AddModelError("", "<p class='field-validation-error'><b>Backup database unsuccessfully.</b></p><p class='field-validation-error'>Folder backup \"" + backupFolder + "\" not found. <br />Please check again system config!</p>");
                        return View(model);
                    }
                    ModelState.AddModelError("", "<p class='field-validation-error'><b>Backup database unsuccessfully.</b></p><p class='field-validation-error'>Please try again in a few minutes</p>");
                }
            }
            return View(model);
        }

        [Authorize]
        [ValidationFunction(ActionName.RESTOREDATABASE)]
        public ActionResult Restore()
        {
            string FilePathXML = HttpContext.Server.MapPath("~/App_Data/Data.xml");
            var doc = XDocument.Load(FilePathXML);

            return View(doc.Descendants("Note").OrderByDescending(m => (int)m.Element("ID")).ToList());
        }

        [HttpGet]
        [Authorize]
        [ValidationFunction(ActionName.RESTOREDATABASE)]
        public ActionResult RestoreByID(string name)
        {

            string pathConfigXML = System.Web.Hosting.HostingEnvironment.ApplicationPhysicalPath + "/App_Data/config.xml";
            // Tạo một đối tượng TextReader mới
            var xtr = System.Xml.Linq.XDocument.Load(pathConfigXML);
            string backupFolder = string.Format(xtr.Element("system.config").Element("path-backup").Value.Trim());
            var dbBackUp = DB.Entities;
            string pathFull = "";
            if ((backupFolder.LastIndexOf("\\") != backupFolder.Length - 1))
            {
                pathFull = backupFolder + "\\" + name;
            }
            else
            {
                pathFull = backupFolder + name;
            }
            if (System.IO.File.Exists(pathFull))
            {
                try
                {
                    string queryCheck = "DECLARE @result INT EXEC master.dbo.xp_fileexist '" + pathFull + "', @result OUTPUT  Select @result";
                    int isExists = dbBackUp.ExecuteStoreQuery<int>(queryCheck, null).FirstOrDefault();
                    if (isExists != 0)
                    {
                        string queryStore = "use master ALTER DATABASE DB_9B22F2_nationalit SET SINGLE_USER With ROLLBACK IMMEDIATE;";
                        queryStore += "RESTORE DATABASE DB_9B22F2_nationalit FROM disk = '" + pathFull + "' WITH REPLACE;";
                        queryStore += "use master ALTER DATABASE DB_9B22F2_nationalit SET MULTI_USER;";
                        queryStore += "use master ALTER DATABASE DB_9B22F2_nationalit SET ONLINE";

                        int result = dbBackUp.ExecuteStoreCommand(queryStore);
                        if (Convert.ToInt32(result) != 0)
                        {
                            ViewBag.Success = "1";
                            return JavaScript(@"alert('Restore database successfully.');");
                        }
                    }
                }
                catch (Exception ex)
                {

                }
            }
            string message = "$('#ModalGeneral').empty().html(\"<div class='modal-header'><a class='close' data-dismiss='modal'>x</a><h3>Error message</h3></div><div class='modal-body'><p class='field-validation-error'><b>Restore database unsuccessfully!</b> <br /> - Please check folder restore in system config: &#34;" + pathFull.Replace("\\", "&#92;") + "&#34;.<br />- Or your user sql server have not permisson restore.</p></div>\").modal('show');";
            return JavaScript(message);
        }


        [Authorize]
        [ValidationFunction(ActionName.RESTOREDATABASE)]
        public ActionResult DeleteBackupDatabaseByID(string name)
        {
            bool success = true;
            string message = "";
            try
            {

                string pathConfigXML = System.Web.Hosting.HostingEnvironment.ApplicationPhysicalPath + "/App_Data/config.xml";
                // Tạo một đối tượng TextReader mới

Views/BackupAndRestore/Backup.cshtml
@model NationalIT.Models.BackupModel
@{
    ViewBag.Title = "Backup database";
}
<script type="text/javascript">
    $(document).ready(function () {
        $('input[name="Name"]').focus();
    });
</script>
<div class="modal-header">
    
    <h3>
        @ViewBag.Title</h3>
</div>
<!--End .modal-header-->
@Html.ValidationSummary(true)
<div class="modal-body" style="padding: 20px 15px 0px 15px;">
    <div class="row-fluid">
        <div class="span12">
            @using (Html.BeginForm("Backup", "BackupAndRestore", new { Class = "form-horizontal well" }))
            {                    
                <fieldset>
                    <div class="control-group">
                        <label class="control-label">
                            Filename backup <span class="error">*</span></label>
                        <div class="controls">
                            @Html.TextBoxFor(m => m.Name, new { Class = "span10" })
                            <span class="help-block">@Html.ValidationMessageFor(m => m.Name)</span>
                        </div>
                    </div>
                    <div class="control-group">
                        <div class="controls">
                            <button class="btn btn-info" type="submit" onclick="$('#choSaoLuu').html($('#dvloader').html());">
                                Backup</button>
                            <a href="@Url.Action("Index")" class="btn" data-dismiss="modal">Cancel</a> <span id="choSaoLuu">
                            </span>
                        </div>
                    </div>
                </fieldset>
            }
        </div>
    </div>
</div>

Views/BackupAndRestore/Index.cshtml
@model List<NationalIT.Models.BackupModel>
@{
    ViewBag.Title = "Backup and restore database";
}
<script type="text/javascript">
    function Loading(name) {
        if (confirm('Are you sure Restore database?')) {
            $(".row-fluid").css('opacity', '0.4');
            $("#dvloader").css({ "opacity": "1", "display": "block" });
            $.ajax({
                url: '@Url.Action("RestoreByID", "BackupAndRestore")',
                data: { 'name': name },
                complete: function () {
                    hideLoading();
                }
            });
        }
    }
    function DeleteBackupData(name) {
        if (confirm('Are you sure DELETE this file backup database?')) {
            $.ajax({
                url: '@Url.Action("DeleteBackupDatabaseByID", "BackupAndRestore")',
                data: { 'name': name },
                dataType: 'json',
                success: function (data) {
                    if (data.IsSuccess) {
                        reloadTableBackupFile();
                    } else {
                        alert(data.Message);
                    }
                }
            });
        };
    }
    function DeleteBackupFileOnline(name) {
        if (confirm('Are you sure DELETE this file backup database?')) {
            $.ajax({
                url: '@Url.Action("DeleteBackupFileOnline", "BackupAndRestore")',
                data: { 'name': name },
                dataType: 'json',
                success: function (data) {
                    if (data.IsSuccess) {
                        location.reload(true);
                    } else {
                        alert(data.Message);
                    }
                }
            });
        };
    }
    function hideLoading() {
        $(".row-fluid").css('opacity', '1');
        $("#dvloader").slideUp();
    }
    function reloadTableBackupFileOnline() {
        $.ajax({
            url: '@Url.Action("ListRestoreOnline", "BackupAndRestore")',
            success: function (data) {
                $('#RestoreOnline').html(data);
            }
        });
    }
    function reloadTableBackupFile() {
        $.ajax({
            url: '@Url.Action("Index", "BackupAndRestore")',
            success: function (data) {
                $('#RestoreData').html(data);
            }
        });
    }
</script>
@if (Model == null)
        {
    <h3 class="heading">
        This feature is no avaiable when system is running on host</h3>
        }
        else
        {
    <div class="row-fluid dataTables_wrapper" style="min-width: 750px;">
        <div class="span12">
            <h3 class="heading">
                List file backup database on server local</h3>
            @if (Model == null)
            {
                <h3 class="heading">
                    This feature is no avaiable when system is running on host</h3>
            }
            else
            {
                <div class="SaoLuuHide">
                    @if (ViewBag.ShowBackupMenu != null && (bool)ViewBag.ShowBackupMenu)
                    { <a class="btn btn-info" href="@Url.Action("Backup", "BackupAndRestore")"> <i class="splashy-box_okay">
                    </i>&nbsp;Backup</a> <a class="btn btn-info" href="@Url.Action("Upload", "BackupAndRestore")">
                        <i class="splashy-box_okay"></i>&nbsp;Upload</a> 
                    }
                </div>
                <div id="RestoreData">
                    @Html.Partial("_RestorePartial", Model)
                </div>
            }
        </div>
    </div>
    
        var bm = new NationalIT.Controllers.BackupAndRestoreController().ListRestoreOnline();

    <div class="row-fluid dataTables_wrapper" style="min-width: 750px;">
        <div class="span12">
            @if (bm == null)
            {
                <h3 class="heading">
                    Some problem when collect files from host. Check your FTP host, user, pass or internet
                    connection</h3>
            }
            else
            {
                <h3 class="heading">
                    List files backup on server online</h3>
                <div class="SaoLuuHide">
                    <a class="btn btn-info" href="@Url.Action("UploadOnline", "BackupAndRestore")"><i
                        class="splashy-box_okay"></i>&nbsp;Upload backup file to host</a>
                </div>
                <div id="RestoreOnline">
                    @Html.Partial("_RestoreOnline", bm)
                </div>
            }
        </div>
    </div>
    }
<div style="display: none; text-align: center" id="dvloader">
    <img src="../../Content/img/loader6.gif" alt="loading" />
</div>
<div class="modal hide fade" id="BackupBox">
</div>

Views/BackupAndRestore/Restore.cshtml
@{
    ViewBag.Title = "Restore database";
}
<div class="row-fluid">
    <div class="span12">
        <h3 class="heading">
            Restore database</h3>
        <div id="RestoreData">
            @Html.Partial("_RestorePartial")
        </div>
    </div>
</div>
<div style="display:none;text-align:center" id="dvloader">
    <img src="../../Content/img/loader6.gif" alt="loading"/>
</div>

Views/BackupAndRestore/Upload.cshtml
@{
    ViewBag.Title = "Upload file to local server";
}
<div class="row-fluid dataTables_wrapper" style="min-width: 750px;">
    <div class="span12">
        <h3 class="heading">
            @ViewBag.Title</h3>
        @Html.ValidationSummary(true)
        @using (Html.BeginForm(null, null, FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <input type="file" name="file" value="" />
            <input type="submit" name="submit" value="Upload" class="btn btn-info" />
            <a href="@Url.Action("Index")" class="btn">Cancel</a>
        }
    </div>
</div>

Views/BackupAndRestore/UploadOnline.cshtml
@{
    ViewBag.Title = "Upload File to Server Online";
}
<div class="row-fluid dataTables_wrapper" style="min-width: 750px;">
    <div class="span12">
        <h3 class="heading">
            @ViewBag.Title</h3>
        @Html.ValidationSummary(true)
        @using (Html.BeginForm(null, null, FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <input type="file" name="file" value="" />
            <input type="submit" name="submit" value="Upload" class="btn btn-info" />
            <a href="@Url.Action("Index")" class="btn">Cancel</a>
        }
    </div>
</div>

Views/BackupAndRestore/_RestoreOnline.cshtml
@model List<NationalIT.Models.BackupModel>
<!-- datatable -->
<script type="text/javascript">
    $(document).ready(function () {
        $("a.Backup").click(function () {
            $(".BackupBox").html($('.waiting').html());
            $.ajax({
                url: "/BackupAndRestore/Backup",
                success: function (data) {
                    $("#BackupBox").html(data);
                }
            });
        });
    });
</script>
<!-- datatable functions -->
<table class="table table-striped table-bordered dTableR">
    <thead>
        <tr>
            <th style="width: 5%" class="center">
                No
            </th>
            <th>
                Filename
            </th>
            <th>
                Backup date
            </th>
            <th>
                Action
            </th>
        </tr>
    </thead>
    <tbody>
        @if (Model.Count > 0)
        {
            int i = 1;
            foreach (var item in Model)
            {
                
            <tr class="rowlink">
                <td style="width: 5%" class="center">
                    @(i++)
                </td>
                <td>
                    @item.Name
                </td>
                <td>
                    @item.Date
                </td>
                <td>
                    <a href="@Url.Action("PushToLocalServer", new { name = item.Name })" class="border" title="Push to local server" >
                            Push to local server</a> | <a href="@Url.Action("DownloadOnlineFile", new { name = item.Name })" class="border" title="Download file restore" >
                            Download</a> | <a href="javascript:void(0)" class="border" title="Delete file restore" onclick="DeleteBackupFileOnline('@item.Name');">
                                Delete</a>
                </td>
            </tr>
            
            }

        }
    </tbody>
</table>

Views/BackupAndRestore/_RestorePartial.cshtml
@model List<NationalIT.Models.BackupModel>
<!-- datatable -->
<script type="text/javascript">
    $(document).ready(function () {
        $("a.Backup").click(function () {
            $(".BackupBox").html($('.waiting').html());
            $.ajax({
                url: "/BackupAndRestore/Backup",
                success: function (data) {
                    $("#BackupBox").html(data);
                }
            });
        });
    });
</script>
<!-- datatable functions -->
<table class="table table-striped table-bordered dTableR">
    <thead>
        <tr>
            <th style="width: 5%" class="center">
                No
            </th>
            <th>
                Filename
            </th>
            <th>
                Backup date
            </th>
            <th>
                Action
            </th>
        </tr>
    </thead>
    <tbody>
        @if (Model.Count > 0)
        {
            int i = 1;
            foreach (var item in Model)
            {
                
            <tr class="rowlink">
                <td style="width: 5%" class="center">
                    @(i++)
                </td>
                <td>
                    @item.Name
                </td>
                <td>
                    @item.Date
                </td>
                <td>
                 <a href="@Url.Action("PushToOnlineServer", new { name = item.Name })" class="border" title="Push to online server" >
                            Push to online server</a> |
                    <a href="javascript:void(0)" class="border" title="Restore database" onclick="Loading('@item.Name');">
                        Restore</a> | <a href="@Url.Action("DownloadFile", new { name = item.Name})" class="border" title="Download file restore" >
                            Download</a> | <a href="javascript:void(0)" class="border" title="Delete file restore" onclick="DeleteBackupData('@item.Name');">
                                Delete</a>
                </td>
            </tr>
            
            }

        }
    </tbody>
</table>