Controllers/CMS/FunctionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NationalIT.Controllers
{
    [Authorize]    
    public class FunctionController : BaseController
    {
        //
        // GET: /Function/

        [Authorize]
        [ValidationFunction(ActionName.SystemAdmin)]
        public ActionResult Index()
        {
            var db = DB.Entities;
            var list = db.mFunction.ToList();
            return View(list);
        }
        [Authorize]
        [ValidationFunction(ActionName.SystemAdmin)]
        public ActionResult Menu(int id)
        {
            try
            {
                var db = DB.Entities;
                var lst = db.mMenu.Where(m => m.mFunction.FirstOrDefault(n => n.ID == id) != null);
                string s = "";
                foreach (var item in db.mMenu)
                {
                    string check = "";
                    if (lst.FirstOrDefault(m => m.ID == item.ID) != null)
                    {
                        check = "checked='checked'";
                    }
                    s += "<label class='checkbox'><input type='checkbox' class='checkitem' " + check + " value='" + item.ID + "' />" + item.Title + "</label>";
                }
                ViewBag.listMenu = s;
                return View(db.mFunction.FirstOrDefault(m => m.ID == id));

            }
            catch (Exception)
            {
                return View();
            }
        }
        [Authorize]
        [HttpPost]
        [ValidationFunction(ActionName.SystemAdmin)]
        public ActionResult Menu(int functionID, string listCheck)
        {
            try
            {
                var db = DB.Entities;
                var function = db.mFunction.FirstOrDefault(m => m.ID == functionID);
                string[] listChecked = listCheck.Split(new char[] { ',' }, StringSplitOptions.RemoveEmptyEntries);
                foreach (var item in db.mMenu)
                {
                    if (listChecked.Contains(item.ID.ToString()))
                    {
                        if (function.mMenu.FirstOrDefault(m => m.ID == item.ID) == null)
                        {
                            function.mMenu.Add(item);
                        }
                    }
                    else
                        if (function.mMenu.FirstOrDefault(m => m.ID == item.ID) != null)
                        {
                            function.mMenu.Remove(item);
                        }
                }

                db.SaveChanges();
                return RedirectToAction("index");
            }
            catch (Exception)
            {
                return View();
            }
        }

    }
}

Controllers/CMS/MenuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NationalIT.Controllers
{
    public class MenuController : BaseController
    {
        [Authorize]
        [ValidationFunction(ActionName.SystemAdmin)]
        public ActionResult Index()
        {
            return View(DB.Entities.mMenu.OrderBy(m=>m.ParentID).ThenBy(m=>m.Oder));
        }

        [Authorize]
        [ValidationFunction(ActionName.SystemAdmin)]
        public ActionResult Create()
        {
            var db = new List<mMenu>();
            var obj = new mMenu() { ID = 0, Title = "None" };
            db.Add(obj);
            db.AddRange(DB.Entities.mMenu);
            SelectList select = new SelectList(db.ToList(), "ID", "Title");
            ViewBag.dropDown = select;
            return View(new mMenu());
        }

        //
        // POST: /CuocPhi/Create

        [HttpPost]
        [Authorize]
        [ValidationFunction(ActionName.SystemAdmin)]
        public ActionResult Create(mMenu model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    // TODO: Add insert logic here
                    var db = DB.Entities;
                    if (model.ParentID == 0)
                    {
                        model.ParentID = null;
                    }
                    if (!model.Oder.HasValue)
                    {
                        model.Oder = 100;
                    }                    
                    model.IsActive = true;
                    db.mMenu.AddObject(model);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                else
                {
                    var lst = new List<mMenu>();
                    var obj = new mMenu() { ID = 0, Title = "None" };
                    lst.Add(obj);
                    lst.AddRange(DB.Entities.mMenu);
                    SelectList select = new SelectList(lst.ToList(), "ID", "Title");
                    ViewBag.dropDown = select;
                    return View();
                }
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /CuocPhi/Edit/5

        [Authorize]
        [ValidationFunction(ActionName.SystemAdmin)]
        public ActionResult Edit(int id)
        {
            var obj = DB.Entities.mMenu.FirstOrDefault(m => m.ID == id);
            var db = new List<mMenu>();
            var dfobj = new mMenu() { ID = 0, Title = "None" };
            db.Add(dfobj);
            db.AddRange(DB.Entities.mMenu);
            SelectList select = new SelectList(db.ToList(), "ID", "Title", DB.Entities.mMenu.FirstOrDefault(m => m.ID == obj.ParentID));
            ViewBag.dropDown = select;

            return View(obj);
        }

        //
        // POST: /CuocPhi/Edit/5

        [HttpPost]
        [Authorize]
        [ValidationFunction(ActionName.SystemAdmin)]
        public ActionResult Edit(mMenu model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    // TODO: Add update logic here
                    var db = DB.Entities;
                    var obj = db.mMenu.FirstOrDefault(m => m.ID == model.ID);
                    obj.Title = model.Title;
                    obj.Oder = model.Oder;
                    if (model.ParentID == 0)
                    {
                        model.ParentID = null;
                    }
                    obj.ParentID = model.ParentID;
                    obj.Url = model.Url;
                    db.ObjectStateManager.ChangeObjectState(obj, System.Data.EntityState.Modified);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                else
                {
                    var obj = DB.Entities.mMenu.FirstOrDefault(m => m.ID == model.ID);
                    var db = new List<mMenu>();
                    var dfobj = new mMenu() { ID = 0, Title = "None" };
                    db.Add(dfobj);
                    db.AddRange(DB.Entities.mMenu);
                    SelectList select = new SelectList(db.ToList(), "ID", "Title", DB.Entities.mMenu.FirstOrDefault(m => m.ID == obj.ParentID));
                    ViewBag.dropDown = select;
                    return View(model);
                }

            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /CuocPhi/Delete/5



        [Authorize]
        [ValidationFunction(ActionName.SystemAdmin)]
        public ActionResult Delete(int id)
        {
            try
            {
                var db = DB.Entities;
                var obj = db.mMenu.FirstOrDefault(m => m.ID == id);
                db.DeleteObject(obj);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        [ValidationFunction(ActionName.SystemAdmin)]
        public string DoActive(int id)
        {
            try
            {
                var db = DB.Entities;
                var obj = db.mMenu.FirstOrDefault(m => m.ID == id);
                obj.IsActive = !obj.IsActive;
                db.ObjectStateManager.ChangeObjectState(obj, System.Data.EntityState.Modified);
                db.SaveChanges();
                if (obj.IsActive == true)
                {
                    return "Đã bật";
                }
                return "<span class='validation-summary-errors'>Đã tắt</span>";
            }
            catch (Exception ex)
            {

                return "";
            }
        }
    }
}

Views/Function/Index.cshtml
@model IEnumerable<NationalIT.mFunction>
<div class="row-fluid">
    <div class="span12">
        <div class="box">
            <div class="box-title">
                <h3>
                    <i class="icon-table"></i>List function</h3>
            </div>
            <div class="box-content">
                <table class="table">
                    <thead>
                        <tr class="table table-hover">
                            <th>
                                Function name
                            </th>
                            <th>
                                List menu
                            </th>
                            <th>
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @item.Title
                                </td>
                                <td>
                                    @foreach (var m in item.mMenu)
                                    {
                                        @m.Title <br />
                                    }
                                </td>
                                <td>
                                    @Html.ActionLink("Add menu", "Menu", new { id = item.ID })
                                </td>                                
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

Views/Function/Menu.cshtml
@model NationalIT.mFunction
<h3>
    Add menu to function: @Model.Title</h3>
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
@Html.ValidationSummary(true, "Add menu unsuccessfully")
@using (Html.BeginForm("Menu", "Function", new { functionID = Model.ID }))
{
    <div>
        @Html.Hidden("listCheck", null, new {id="HiddenListRole"})
        <div class="control-group">
            <label class="control-label">
                List Menu</label>
            <div class="controls" id="ListRoles">
                <label class="checkbox" style="padding-bottom:5px; width:170px; border-bottom:1px solid #0e6390">
                    <input type="checkbox" class="checkAll" value="" />
                    Check All
                </label>                
                @Html.Raw(ViewBag.listMenu)
            </div>
            <input type="submit" value="OK" class="btn btn-primary" id="SubmitRole" />
            @Html.ActionLink("Cancel", "index", null, new { @class = "btn" })
        </div>
    </div>
}