Controllers/CMS/FunctionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NationalIT.Controllers
{
    [Authorize]    
    public class FunctionController : BaseController
    {
        //
        // GET: /Function/

        [Authorize]
        [ValidationFunction(ActionName.SystemAdmin)]
        public ActionResult Index()
        {
            var db = DB.Entities;
            var list = db.mFunction.ToList();
            return View(list);
        }
        [Authorize]
        [ValidationFunction(ActionName.SystemAdmin)]
        public ActionResult Menu(int id)
        {
            try
            {
                var db = DB.Entities;
                var lst = db.mMenu.Where(m => m.mFunction.FirstOrDefault(n => n.ID == id) != null);
                string s = "";
                foreach (var item in db.mMenu)
                {
                    string check = "";
                    if (lst.FirstOrDefault(m => m.ID == item.ID) != null)
                    {
                        check = "checked='checked'";
                    }
                    s += "<label class='checkbox'><input type='checkbox' class='checkitem' " + check + " value='" + item.ID + "' />" + item.Title + "</label>";
                }
                ViewBag.listMenu = s;
                return View(db.mFunction.FirstOrDefault(m => m.ID == id));

            }
            catch (Exception)
            {
                return View();
            }
        }
        [Authorize]
        [HttpPost]
        [ValidationFunction(ActionName.SystemAdmin)]
        public ActionResult Menu(int functionID, string listCheck)
        {
            try
            {
                var db = DB.Entities;
                var function = db.mFunction.FirstOrDefault(m => m.ID == functionID);
                string[] listChecked = listCheck.Split(new char[] { ',' }, StringSplitOptions.RemoveEmptyEntries);
                foreach (var item in db.mMenu)
                {
                    if (listChecked.Contains(item.ID.ToString()))
                    {
                        if (function.mMenu.FirstOrDefault(m => m.ID == item.ID) == null)
                        {
                            function.mMenu.Add(item);
                        }
                    }
                    else
                        if (function.mMenu.FirstOrDefault(m => m.ID == item.ID) != null)
                        {
                            function.mMenu.Remove(item);
                        }
                }

                db.SaveChanges();
                return RedirectToAction("index");
            }
            catch (Exception)
            {
                return View();
            }
        }

    }
}

Controllers/CMS/RoleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NationalIT.Controllers
{
    public class RoleController : BaseController
    {
        //
        // GET: /Role/

        [Authorize]
        [ValidationFunction(ActionName.SystemAdmin)]
        public ActionResult Index()
        {
            return View(DB.Entities.mRole);
        }

        [Authorize]
        [ValidationFunction(ActionName.SystemAdmin)]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Authorize]
        [ValidationFunction(ActionName.SystemAdmin)]
        public ActionResult Create(mRole model)
        {
            try
            {
                // TODO: Add insert logic here
                var db = DB.Entities;
                var role = new mRole() { Name = model.Name };
                db.mRole.AddObject(role);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        [Authorize]
        [ValidationFunction(ActionName.SystemAdmin)]
        public ActionResult Edit(int id = 0)
        {
            var obj = DB.Entities.mRole.First(m => m.ID == id);
            if (obj == null)
                return RedirectToAction("Index");
            return View(obj);
        }

        [HttpPost]
        [Authorize]
        [ValidationFunction(ActionName.SystemAdmin)]
        public ActionResult Edit(mRole model)
        {
            try
            {
                // TODO: Add update logic here
                var db = DB.Entities;
                var obj = db.mRole.First(m => m.ID == model.ID);
                obj.Name = model.Name;
                db.ObjectStateManager.ChangeObjectState(obj, System.Data.EntityState.Modified);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        [Authorize]
        [ValidationFunction(ActionName.SystemAdmin)]
        public ActionResult Delete(int id)
        {
            try
            {
                var db = DB.Entities;
                var obj = db.mRole.First(m => m.ID == id);
                db.mRole.DeleteObject(obj);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return RedirectToAction("Index");
            }
        }

        [Authorize]
        [ValidationFunction(ActionName.SystemAdmin)]
        public ActionResult Function(int id)
        {
            try
            {
                var db = DB.Entities;
                var lst = db.mFunction.Where(m => m.mRole.FirstOrDefault(n => n.ID == id) != null);
                string s = "";
                foreach (var item in db.mFunction)
                {
                    string check = "";
                    if (lst.FirstOrDefault(m => m.ID == item.ID) != null)
                    {
                        check = "checked='checked'";
                    }
                    s += "<label class='checkbox'><input type='checkbox' class='checkitem' " + check + " value='" + item.ID + "' />" + item.Title + "</label>";
                }
                ViewBag.listFuntion = s;
                return View(db.mRole.FirstOrDefault(m => m.ID == id));

            }
            catch (Exception)
            {
                return View();
            }
        }

        [Authorize]
        [ValidationFunction(ActionName.SystemAdmin)]
        public ActionResult DoFunction(int roleID, string listCheck)
        {
            try
            {
                var db = DB.Entities;
                var role = db.mRole.FirstOrDefault(m => m.ID == roleID);
                string[] listChecked = listCheck.Split(new char[] { ',' }, StringSplitOptions.RemoveEmptyEntries);
                foreach (var item in db.mFunction)
                {
                    if (listChecked.Contains(item.ID.ToString()))
                    {
                        if (role.mFunction.FirstOrDefault(m => m.ID == item.ID) == null)
                        {
                            role.mFunction.Add(item);
                        }
                    }
                    else
                        if (role.mFunction.FirstOrDefault(m => m.ID == item.ID) != null)
                        {
                            role.mFunction.Remove(item);
                        }
                }

                db.SaveChanges();
                return RedirectToAction("index");
            }
            catch (Exception)
            {
                return View();
            }
        }
    }


}


Views/Role/Create.cshtml
@model NationalIT.mRole
<h3>
    Add new a role </h3>
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
@Html.ValidationSummary(true, "Add new unsuccessfully")
@using (Html.BeginForm("Create", "Role"))
{
    <div>
        <div class="control-group">
            <label class="control-label">
                Role name</label>
            <div class="controls">
                @Html.TextBoxFor(m => m.Name)
            </div>
            <input type="submit" value="OK" class="btn btn-primary"/>
            <button type="button" class="btn" onclick="javascript:window.history.go(-1);">
                Cancel</button>
        </div>
    </div>
}

Views/Role/Edit.cshtml
@model NationalIT.mRole
<h3>
    Edit role
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
@Html.ValidationSummary(true, "Edit role unsuccessfully")
@using (Html.BeginForm("Edit", "Role", new { groupID = ViewBag.GroupID }))
{
    <div>
        <div class="control-group">
            <label class="control-label">
                Role name</label>
            <div class="controls">
                @Html.TextBoxFor(m => m.Name)
            </div>
            <input type="submit" value="OK" class="btn btn-primary"/>
            <button type="button" class="btn" onclick="javascript:window.history.go(-1);">
                Cancel</button>
        </div>
    </div>
}

Views/Role/Function.cshtml
@model NationalIT.mRole
<h3>
    Add function to: <a href="/Group/UsersInGroup/@Model.ID">@Model.Name</a></h3>
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
@Html.ValidationSummary(true, "Add new unsuccessfully")
@using (Html.BeginForm("DoFunction", "Role", new { roleID = Model.ID }))
{
    <div>
        @Html.Hidden("listCheck", null, new { id = "HiddenListRole" })
        <div class="control-group">
            <label class="control-label">
                List Function</label>
            <div class="controls" id="ListRoles">
                <label class="checkbox" style="padding-bottom:5px; width:170px; border-bottom:1px solid #0e6390">
                    <input type="checkbox" class="checkAll" value="" />
                    Check All
                </label>           
                @Html.Raw(ViewBag.listFuntion)
            </div>
        </div>
        <div class="control-group">
            <input type="submit" value="OK" class="btn btn-primary" id="SubmitRole" />
            @Html.ActionLink("Cancel", "index", null, new { @class = "btn" })
        </div>
    </div>
}

Views/Role/Index.cshtml
@model IEnumerable<NationalIT.mRole>
<div class="row-fluid">
    <div class="span12">
        <div class="box">
            <div class="box-title">
                <h3>
                    <i class="icon-table"></i>List role</h3>
            </div>
            <div class="box-content">
                <p style="margin-left: 7px;">
                    @Html.ActionLink("Add a new role", "Create", null, new { @class = "btn btn-primary" })
                </p>
                <table class="table">
                    <thead>
                        <tr class="table-flag-blue">
                            <th>
                                Role name
                            </th>
                            <th>
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>                                
                                <td>
                                    @Html.ActionLink(item.Name, "Edit", new { id = item.ID })
                                </td>
                                <td>
                                    @Html.ActionLink("Add function to role", "Function", new { id = item.ID })
                                </td>
                                <td>
                                    @Html.ActionLink("Delete", "Delete", new { id = item.ID }, new { @class = "confirmDelete" })
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>